import "../globals.scss";
import styles from "./layout.module.scss";
import Link from "next/link";
import CountDown from "@/components/MainPage/CountDown";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <header>
                    <div className={styles.logo}>
                        <h1>SECIM2023</h1>
                        <CountDown />
                    </div>

                    <div className={styles.menu}>
                        <ul>
                            <li>
                                <Link href="/">Seçim 2023</Link>
                            </li>
                            <li>
                                <Link href="/anket">Anket Sonuçları</Link>
                            </li>
                            <li>
                                <Link href="/youtube">
                                    Youtube Sokak Röportajları
                                </Link>
                            </li>
                        </ul>
                    </div>
                </header>

                <div className={styles.content}>{children}</div>
            </body>
        </html>
    );
}
